// orient-express.md | RecursiveChunkingStrategy | size=150
export default [
  // Chunk 1
  "# Orient-Express\n\n**Blanche El Gammal**\n\n---\n\n**Référence électronique**\n\nBlanche El Gammal, *Orient-Express*. Publictionnaire. Dictionnaire encyclopédique et critique des publics. Mis en ligne le 13 décembre 2023. Accès : https://publictionnaire.huma-num.fr/notice/orient-express/\n\nLe Publictionnaire. Dictionnaire encyclopédique et critique des publics est un dictionnaire collaboratif en ligne sous la responsabilité du Centre de recherche sur les médiations (Crem, Université de Lorraine) ayant pour ambition de clarifier la terminologie et le profit heuristique des concepts relatifs à la notion de public et aux méthodes d'analyse des publics pour en proposer une cartographie critique et encyclopédique.\n\nAccès : https://publictionnaire.huma-num.fr\n\n*Cette notice est mise à disposition selon les termes de la licence Creative Commons Attribution - Pas d'utilisation commerciale - Pas de modification 3.0 France.*\n\n---",

  // Chunk 2
  "Conçu et perçu comme un hôtel sur rail, il est pour ses passagers une sorte de tapis magique reliant Paris à Constantinople en un peu moins de trois jours. Paré de toutes les séductions dans l'imaginaire collectif, il est associé à l'Orient, au luxe, à la Belle Époque, aux Années Folles, aux grands personnages qui l'ont pris ou supposément pris, comme Mata Hari (1876-1917) ou Joséphine Baker (1906-1975), au célèbre *Crime* d'Agatha Christie (1890-1976). Son histoire n'est pourtant pas réductible à ces beaux mots et ces noms prestigieux, lesquels relèvent pour une part d'une doxa qui n'a cessé de s'embellir au fil des années. Si d'indispensables données historiques et géographiques doivent être ici rappelées, l'accent sera mis sur le public des voyageurs, les images qui en sont données dans la littérature et les multiples formes de publicité qui ont fait la renommée du train.",

  // Chunk 3
  "1900. Source : Wikimedia (domaine public).*\n\n---\n\n## Le projet et les débuts (1870-1914)\n\nL'Orient-Express, on s'en doute, n'a pas été créé *ex nihilo*. Son inventeur, l'ingénieur liégeois **Georges Nagelmackers** (1845-1905), s'est rendu aux États-Unis dans les années 1860 et a rapporté de son voyage deux idées qui doivent aux réalisations de l'industriel George M. Pullman (1831-1897). La première est la suivante : de même que les États américains ont été reliés par le chemin de fer, de même le train, et en particulier l'Orient-Express, devra relier les États qu'il traverse en Europe (Des Cars, Caracalla, 1984 : 16). La seconde idée consiste à reproduire, avec quelques adaptations et améliorations, le luxe des voitures américaines, réputées très confortables. De retour en Europe, G. Nagelmackers publie en 1870 une plaquette intitulée *Projet d'installation de wagons-lits sur les chemins de fer du continent*.",

  // Chunk 4
  "ne connaît ni les trains internationaux, ni les trains de luxe. Il est donc audacieux, mais G. Nagelmackers peut compter sur le soutien des membres de sa très influente famille, une des plus puissantes à Liège : son grand-père était le fondateur de la très réputée Banque Nagelmackers ; son père est ingénieur ; son oncle Walthère Frère-Orban (1812-1896) est une personnalité de premier ordre, ingénieur lui aussi, fondateur du parti libéral de Belgique en 1846, ministre des Finances puis Premier ministre du royaume. Ses cousins de la famille Orban, banquiers, ingénieurs et juristes, facilitent aussi les contacts dans le milieu des affaires et de la finance. Last but not least, Nagelmackers obtient l'appui du roi des Belges, Léopold II (1835-1909) (Mettetal, 2022 : 49-52).",

  // Chunk 5
  "voies ferroviaires que doivent emprunter les nouveaux trains ne sont pas encore achevées. G. Nagelmackers parvient néanmoins à convaincre les États et les administrations ferroviaires de l'intérêt de faire circuler sur leurs territoires et leurs réseaux des trains de luxe internationaux (ibid. : 23). Après des changements de noms et de statuts, la **Compagnie Internationale des Wagons-Lits** est créée en 1876. L'Orient-Express est le premier train de luxe international de la Compagnie et donc son fleuron, mais c'est en fait un train parmi d'autres (songeons au Nord-Express, au Sud-Express ou au Transsibérien).",

  // Chunk 6
  "l'achèvement des tronçons serbe et bulgare, le trajet se fait exclusivement par voie terrestre par Belgrade et Sofia à partir de 1889. Il est aussi possible de traverser la mer Noire à destination de Constantinople depuis Constantza, en Roumanie, à partir de 1895.\n\n*Les routes de l'Orient-Express, de son lancement en 1883 à la Première Guerre mondiale. Source : Wikimedia (CC BY-SA 3.0).*\n\nConstantinople, c'est la Sublime Porte de l'Orient chantée par tout le XIXe siècle et le courant orientaliste, qu'il s'agisse des poètes ou des peintres. L'arrivée de l'Orient-Express dans la ville est aussi contemporaine des romans turcs de **Pierre Loti** (1850-1923), qui connaissent un grand succès — citons *Aziyadé* (1878), *Fantôme d'Orient* (1892) et *Les Désenchantées* (1906).",

  // Chunk 7
  ": ainsi des coloris chauds, des portes aux formes arrondies et des mosquées aux minarets élevés.\n\nConstantinople est aussi, plus concrètement, une ville où les influences européennes sont très présentes depuis que les sultans ottomans ont lancé en 1839 le programme de modernisation des Tanzimat (« réorganisation »), marqués par la construction de nombreux bâtiments situés à Galata, sur la rive européenne : la colline de Péra est le quartier d'affaires de la ville, avec ses banques, ses clubs, ses théâtres, ses hôtels. L'Orient-Express, à cet égard, accélère l'occidentalisation de la ville, au grand dam de Pierre Loti, pour qui Stamboul est irrémédiablement abîmé (Collet, 1997).",

  // Chunk 8
  "hôtels de la Compagnie Internationale des Grands Hôtels, fondée en 1894 par G. Nagelmackers. Ce peut être par exemple au célèbre **Péra Palace** de Constantinople : cet hôtel de luxe, le premier de la ville à avoir l'électricité en 1900, est situé précisément à Galata et offre une vue magnifique sur le Bosphore. En somme, c'est un peu le voyage *all inclusive* avec option *hop-on hop-off* dans sa version luxueuse.\n\n---\n\n## Le public prestigieux d'un train de luxe entre deux siècles",

  // Chunk 9
  "en délégations. Ainsi, à l'occasion d'un voyage organisé par les autorités hongroises en 1885, la Coupole est réunie dans le train : quarante académiciens se rendent à Budapest, parmi lesquels le musicien Jules Massenet (1842-1912), Ferdinand de Lesseps (1805-1894), le gynécologue du Tout-Paris Samuel Pozzi (1846-1918) et le poète François Coppée (1842-1908) (Montet, 1886).\n\nC'est le train de la Belle Époque, des voyageurs cosmopolites du monde d'hier, comme la très francophile famille roumaine Bibesco ; comme l'écrivain autrichien Stefan Zweig (1881-1942), qui invite régulièrement des auteurs européens dans sa maison de Salzbourg ; comme Valery Larbaud (1881-1957), auteur d'une célèbre « Ode » aux trains de luxe. Tous sont nés dans les mêmes années, avec le train pour ainsi dire, qu'ils ont connu très jeunes et dont ils ont subi le charme.",

  // Chunk 10
  "train créé par et pour les Occidentaux qui se ruent sur les marchés ouverts par l'effondrement de l'Empire ottoman, qui a perdu en 1878 au Traité de Berlin une partie de ses territoires serbes, roumains et bulgares ; or ces pays des Balkans doivent encore être dotés de nombreuses infrastructures.\n\nC'est un train extrêmement cher, et il n'est pas exagéré de dire que c'est un palace sur rail ; ça l'est au sens propre, puisqu'il faut reproduire le luxe des hôtels que fréquente la clientèle, d'où la présence de matériaux nobles (cuir de Cordoue, velours de Gênes) et d'un mobilier de style Louis XV dans les voitures. Le luxe consiste aussi à ne pas devoir changer de train au passage des frontières et à se déplacer vite : l'Orient-Express est le moyen de transport le plus rapide pour se rendre d'une grande ville du parcours à Constantinople.",

  // Chunk 11
  "lors que les notes exaltées abondent dans les récits de voyage ou dans la correspondance des *happy few* qui empruntent à l'occasion ou régulièrement l'Orient-Express : c'est à la fois le train des hommes d'affaires puissants, des ingénieurs de talent, des têtes couronnées et d'une élite intellectuelle et artistique.\n\nL'effet tapis magique opère et pourtant... Le projet d'unifier l'Europe par l'Orient-Express est grandement compromis d'entrée de jeu. Le train a été créé sur fond de guerre latente : c'est bien sûr la défaite de la France contre l'Allemagne en 1871 (la traversée de Strasbourg est douloureusement vécue par les voyageurs français, qui tiennent des propos amers et acerbes), mais il y a aussi des conflits dans les Balkans : dès la fin du siècle, les Macédoniens bulgares mécontents des partages décidés par les grandes puissances au Traité de Berlin commettent plusieurs attentats sur le parcours oriental du train.",

  // Chunk 12
  "veulent faire sauter l'Orient-Express pour alerter l'opinion internationale de leur sort ; or la situation dans les Balkans s'aggrave avec les guerres balkaniques de 1912-1913. Toutes ces tensions sont visibles à l'intérieur et à l'extérieur du train : en témoignent les conversations inquiètes des voyageurs, qui ont conscience de parcourir une route armée à l'approche de la Première Guerre mondiale (Lauzanne, 1913).\n\n---\n\n## Le train à l'épreuve de l'Histoire : l'évolution des trajets et des voyageurs (1914-1977)\n\nLe train est arrêté en juillet 1914. Pendant la guerre, il est repris et détourné de son trajet par la compagnie allemande Mitropa. L'Orient-Express devient le **Balkanzug**, le train des Balkans reliant Berlin à Constantinople par les pays alliés à l'Allemagne : l'idée est d'en faire le premier tronçon de la Bagdadbahn, le grand projet de Guillaume II (1859-1941) visant à relier Berlin au Moyen-Orient.",

  // Chunk 13
  "Wikimedia (CC BY-SA 3.0).*\n\nL'Orient-Express change d'itinéraire après-guerre. Dès le début du siècle s'était manifestée une volonté de faire concurrence à la ligne de l'Orient-Express, très favorable, en termes de parcours et de partenariat économique, à l'Allemagne et à ses voisins. Le projet d'une route méridionale par le tunnel séparant la Suisse de l'Italie, le Simplon, déjà évoqué en 1906, est repris après-guerre et porté par Paul Claudel (1868-1955). Un nouveau train est créé, le **Simplon-Orient-Express**, dit aussi train de l'Europe nouvelle, et un nouveau parcours, ou route interalliée. Cette route évite l'Allemagne, l'Autriche et la Hongrie et passe par les pays suivants : la France, la Suisse, que le train quitte pour gagner l'Italie en franchissant le tunnel du Simplon (d'où le nom du train), le Royaume des Serbes, des Croates et des Slovènes, rebaptisé Yougoslavie en 1929.",

  // Chunk 14
  "Constantinople.\n\n*Les Orient-Express dans l'entre-deux-guerres. Source : Wikimedia (CC BY-SA 3.0).*\n\nL'Orient-Express classique est relancé deux ans après sur son parcours originel mais il est désormais très concurrencé par le nouveau train, avec lequel il est souvent confondu. Le conseil d'administration de la Compagnie Internationale des Wagons-Lits après-guerre est essentiellement français et anglais. Les années 1920 sont un tournant, et l'âge d'or de la Compagnie dirigée par **lord Davison Dalziel** (1852-1928), baron anglais et beau-père de l'unique fils de Georges Nagelmackers, René (1878-1929). D. Dalziel engage deux actions principales : la britannisation du train avec des liaisons renforcées entre Londres et Paris via la gare de Calais-Maritime et l'introduction des voitures britanniques Pullman, réputées les plus belles en Europe.",

  // Chunk 15
  "Pullman sont décorées par de célèbres artisans d'art, comme **René Prou** (1887-1947) et **René Lalique** (1860-1945). C'est aussi le temps des affiches Art Déco signées par de grands noms, à l'instar de **Cassandre** (1901-1968). L'Orient-Express devient donc un objet d'art (Mettetal, 2022 : 259-290).\n\nÀ cela s'ajoute un formidable essor de la Compagnie avec la multiplication et le prolongement des lignes : outre le Simplon-Orient-Express, l'Arlberg-Express, emprunté par les nombreux amateurs de paysages autrichiens, devient l'Arlberg-Orient-Express en 1932 ; surtout, la Compagnie lance le **Taurus-Express** en 1930, année où Constantinople devient Istanbul : à partir de la rive asiatique de la ville, on peut désormais atteindre Bagdad-Bassora à l'est, Jérusalem-Le Caire à l'ouest.",

  // Chunk 16
  "gain de temps de 24 heures est possible à partir de 1940, avec l'achèvement des tronçons ferroviaires manquants, par exemple entre Mossoul et Bagdad. C'est en fait là le rêve de la Bagdadbahn, initié par Guillaume II au début du siècle, qui devient réalité, mais récupéré à leur profit par les Français et les Britanniques, qui détiennent respectivement des mandats en Syrie et en Irak. Cette nouvelle mainmise est rendue possible par les travaux assez largement entamés de la Bagdadbahn, dont le chantier a été interrompu en 1912 à Alep, mais aussi grâce à l'amélioration progressive des relations entre la Turquie et l'Irak. Dès lors, on peut envisager, à partir de Bassora, de gagner Bombay. D'une certaine façon, les Anglais réalisent un grand projet qui remonte aux années 1850 : celui de bâtir une « world's highway » qui irait de l'Europe du Nord à l'Inde.",

  // Chunk 17
  "est aussi le train des Années Folles associé aux images de luxe, d'insouciance et de grivoiserie véhiculées par *La Madone des Sleepings*, héroïne du best-seller de **Maurice Dekobra** (1885-1973) paru en 1925.\n\nLe propos doit toutefois être nuancé. À côté de toutes ces enthousiasmantes réalisations, de nouvelles classes sont introduites (il n'y avait qu'une classe jusqu'ici), donc de nouvelles populations : ce sont les exilés, les malheureux, les trafiquants et les criminels qu'on retrouve dans toute la littérature Orient-Express de l'entre-deux-guerres, qui est particulièrement sombre. **Paul Morand** (1888-1976 ; 1922) évoque ainsi des voyageurs du Simplon-Orient-Express harassés dans « La nuit turque » ; on y voit des couturières, des modistes, des femmes du Civil Service et un escroc se côtoyer dans le plus grand inconfort (ibid. : 73-75).",

  // Chunk 18
  "de regagner l'argent qu'elle a perdu dans des placements inconsidérés (Dekobra, 1925 : 307-313). C'est son chevalier servant Gérard qui prend les grands express ; ses aventures ferroviaires à elle appartiennent au passé. Les années 1930 sont plus noires encore dans la littérature Orient-Express, et on ne trouve pas un seul éloge du train ou de ses voyageurs dans le *Crime* d'A. Christie. À l'image d'Hercule Poirot observant ses compagnons de voyage avec circonspection, il n'est pas rare de se demander qui au juste fait route avec vous (Christie, 1934 : 24-30). C'est la défiance qui règne, non le climat euphorique des premiers voyages.",

  // Chunk 19
  "son roman de ses propres voyages et de faits divers qui ont nourri l'actualité (le train pris dans une tempête de neige en 1929 et l'assassinat du bébé Lindbergh en 1932). Ces écrits sont donc presque des chroniques, à tout le moins reflètent l'air du temps ; sans compter qu'on trouve occasionnellement dans la presse quotidienne des récits de trafics, d'agressions, de crimes et de voyages clandestins dans l'Orient-Express (El Gammal, 2017 : 221-222 ; 2021). Aussi les Années folles et les années sombres se côtoient-elles sans véritable solution de résorption : ce qui est sûr, c'est que des individus suspects, dangereux ou repoussants circulent désormais dans le train aux côtés des voyageurs habituels.",

  // Chunk 20
  "peu, victime de la concurrence de l'avion et des tensions de la Guerre froide. La traversée du rideau de fer en Yougoslavie crée des retards et le trajet est interminable, ce qui est manifeste dans *Bons Baisers de Russie* (1957), où James Bond prend le train à Istanbul à destination de Paris (Fleming, 1957 : 721-764). Le public des années 1950, 1960 et 1970 change, là encore, avec quelques voyageurs inattendus, comme des hippies se rendant à Istanbul, étape importante du *hippie trail* sur la route de Katmandou. On ne s'étonnera pas de les voir consommer ou transporter des substances illicites dans les wagons fatigués de l'Orient-Express, comme c'est le cas de la jeune Tooley dans *Voyages avec ma tante* de Graham Greene (1904-1991 ; 1969 : 133-143).",

  // Chunk 21
  "de notes nécrologiques qui reviennent avec nostalgie sur les belles années de l'Orient-Express. Mais si l'on fait ses adieux au train, on ne peut visiblement pas s'en passer, et c'est pourquoi, après plusieurs coups d'arrêt sérieux et un dernier voyage à Istanbul en 1977, il ressuscite encore de ses cendres.\n\n---\n\n## La renaissance du train et de la marque Orient-Express (depuis 1982)\n\nOn compte plusieurs résurrections du train, la première ayant lieu avant le dernier voyage de 1977, curieusement. Elle consiste dans le rachat de voitures par **Albert Glatt**, patron de l'agence de voyages suisse Intraflug, spécialisée dans les vols charters entre l'Angleterre et l'Espagne. Il crée en 1976 le **Nostalgie Istanbul Orient-Express**, qui circule entre Zurich et Istanbul et connaît un certain succès, jusqu'à son arrêt dans les années 2000.",

  // Chunk 22
  "mois seulement après le dernier voyage de l'Orient-Express, l'Américain **James Sherwood**, patron de la Sea Containers, rachète deux wagons très défraîchis de l'Orient-Express lors d'une vente aux enchères à Monaco. Il achète ensuite une vingtaine de voitures chez des ferrailleurs et des collectionneurs, qu'il restaure à grands frais (Sherwood, 1984). J. Sherwood lance en 1982 le **Venice Simplon Orient-Express**, qui circule entre Londres et Venise ou Vérone via Paris plusieurs fois par semaine. Il dessert parfois les villes de Berlin, Vienne, Prague et Budapest, et fait une fois par an le trajet Paris-Istanbul. Le train permet aux voyageurs de revivre l'expérience de l'Orient-Express à son âge d'or. En effet, il est composé de dix-sept voitures d'origine restaurées — onze voitures-lits, trois voitures-restaurants, une voiture-bar et deux voitures pour le personnel — avec tout le confort d'époque. Au moment où il lance son train, J.",

  // Chunk 23
  "venir les riches Britanniques jusqu'à Venise où il vient de racheter l'hôtel Cipriani, créant simultanément le groupe hôtelier de luxe **Belmond**. Le Venice Simplon Orient-Express circule encore aujourd'hui mais l'entreprise Belmond a été rachetée par le groupe **LVMH** en 2019.\n\nLa troisième résurrection du train est relativement récente. Elle comprend plusieurs étapes et devrait bientôt voir le jour. Tout commence en 2011, quand la SNCF décide du rachat de sept voitures historiques de la Compagnie. En 2014, le projet de relance de l'Orient Express est amorcé avec l'exposition *Il était une fois l'Orient-Express* (Clémente-Ruiz, 2014), coproduite par l'Institut du monde arabe, qui présente notamment quatre voitures sur son parvis, et la direction de la communication du groupe SNCF. En janvier 2015, la filiale Orient-Express est créée afin d'accompagner la renaissance de la marque.",

  // Chunk 24
  "de combiner voyage en train et séjour à l'hôtel, comme l'avaient fait G. Nagelmackers puis J. Sherwood.\n\nAccor a annoncé que l'**Orient Express La Dolce Vita** devrait accueillir ses premiers passagers en 2024. Six trains composés de 11 voitures traverseront 14 régions d'Italie. Ces trains présentent des décors somptueux conçus par Dimorestudio, studio d'architecture et de design milanais fondé en 2003 par Emiliano Salci et Britt Moran, tous les deux inspirés par l'artisanat d'art et l'âge d'or du design italien. La marque Orient-Express lancera également ses premiers hôtels en 2024, avec des emplacements à Rome, Venise et Riyad.",

  // Chunk 25
  "au groupe Belmond pour l'exploitation de trente-quatre hôtels et un train de luxe, lesquels s'appelaient Orient-Express. Mais en 2011, la direction de la SNCF a engagé des négociations avec Belmond pour récupérer son droit d'utilisation de la marque. Le groupe SNCF a repris l'exploitation du nom Orient-Express dans le domaine de l'hôtellerie en échange d'une prolongation de 75 ans de la licence ferroviaire qui permet au groupe Belmond d'exploiter le nom de Venice Simplon Orient-Express. En 2014, la totalité des hôtels Orient-Express ont donc été renommés Belmond.",

  // Chunk 26
  "de la photographie d'Arles en 2021, montrée à la Villa Médicis dans sa version italienne, Paris-Rome Express (Orient Express La Dolce Vita oblige).\n\nLe fait est moins connu mais parallèlement à ces résurrections matérielles du train, beaucoup d'ouvrages littéraires, depuis les années 1980, exploitent le filon Orient-Express et ses deux grands thèmes préférés : l'amour et le crime, entre nostalgie et humour. Là aussi, le nom Orient-Express est un sésame : c'est la saga Orient-Express de **Pierre-Jean Rémy** (1979 ; 1984) en deux volumes adaptée à la télévision, les détournements parodiques de titres autour de la Madone des Sleepings (Benacquista, 1989 ; San-Antonio, 1993), qui a indubitablement contribué à la renommée de l'Orient-Express — le roman a d'ailleurs été réédité en 2006.\n\n---",

  // Chunk 27
  "de lui, toutes périodes confondues : pensons aux récits enthousiastes des journalistes vedettes invités par G. Nagelmackers lors du voyage inaugural de 1883. Edmond About (1828-1885 ; 1884), romancier bien connu et journaliste au XIXe siècle, et Henri Opper de Blowitz (1825-1903 ; 1884), journaliste au *Times*, considéré comme le père de l'interview moderne, y vantent la prodigalité de leur hôte, qui leur a réservé des mets savoureux, des pauses musicales et même une visite au beau château de Peleș en Roumanie, où les ont accueillis le roi et la reine ; or ces récits sont toujours cités par les thuriféraires de l'Orient-Express.",

  // Chunk 28
  "mythe du train chéri des écrivains, de P. Morand, A. Christie et G. Greene, lesquels n'ont jamais écrit une ligne favorable au train, sauf, s'agissant de P. Morand, quand J.-P. Caracalla lui a commandé un « Adieu au train » dans les années 1960. Enfin, dans les années 2020, il y a un battage médiatique autour de la bataille entre Accor/SNCF et LVMH.\n\n---\n\nMais revenons au projet de G. Nagelmackers, qui était l'union des États européens. Force est de constater, au regard de l'Histoire, que l'Orient-Express n'a fait que révéler leur désunion ; le train a été victime des guerres qui ont sévi en Europe.",

  // Chunk 29
  "*slow travel* mais à ses débuts, l'Orient-Express était le moyen de transport le plus rapide et les voyageurs pestaient lorsque le train décélérait). Il y a plusieurs Orient-Express, plusieurs parcours, plusieurs périodes, plusieurs types de voyageurs. Aussi ne peut-on pas tenir de discours totalement univoque au sujet de ce train, qui garde une part d'ombre même lorsque tous les projecteurs révèlent ses splendeurs. Il est et n'est pas seulement le train que chacun se représente.\n\n---\n\n## Bibliographie",

  // Chunk 30
  "légendaire désormais partagé entre Accor et LVMH », *Challenges*, 22 juin.\n- Dekobra M., 1925, *La Madone des Sleepings*, Paris, Zulma, 2006.\n- Des Cars J., Caracalla J.-P., 1984, *L'Orient-Express, un siècle d'aventures ferroviaires*, Paris, Denoël.\n- El Gammal B., 2017, *L'Orient-Express. Du voyage extraordinaire aux illusions perdues*, Paris, Éd. Les Belles Lettres.\n- El Gammal B., 2021, *L'Orient-Express raconté par les écrivains*, Paris, Éd. Phébus/Éd. Libella.\n- Fleming I., 1957, *Bons baisers de Russie*, trad. de l'anglais par A. Gilliard, Paris, R. Laffont, 2011.\n- Greene G., 1969, *Voyages avec ma tante*, trad. de l'anglais par G. Belmont, Paris, Éd. 10/18, 2009.\n- Lauzanne S., 1913, *Au chevet de la Turquie. Quarante jours de guerre*, Paris, A. Fayard.",

  // Chunk 31
  "- Montet J., 1886, *De Paris aux Karpathes*, Paris, Hachette.\n- Morand P., 1922, « La nuit turque », in : *Ouvert la nuit*, Paris, Gallimard.\n- Morand P., 1962, « Adieu à l'Orient-Express », in : *Le Voyage*, Paris, A. Fayard, 1996.\n- Nagelmackers G., 1870, *Projet d'installation de wagons-lits sur les chemins de fer du continent*, Liège, H. Vaillant-Carmanne & Cie.\n- Opper de Blowitz H., 1884, *Une course à Constantinople*, Paris, Plon/Nourrit et Cie.\n- Rémy P.-J., 1979, *Orient-Express*, Paris, A. Michel.\n- Rémy P.-J., 1984, *Orient-Express 2*, Paris, A. Michel.\n- San-Antonio, 1993, *La Matrone des sleepinges*, Paris, Éd. Fleuve noir.\n- Sherwood S., 1984, *Venise Simplon Orient-Express. Le plus célèbre train du monde reprend du service*, Paris, Payot.",

];
